version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/capitan/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  mysql:
    image: mysql:5.7
    volumes:
      - ~/.docker-volumes/capitan/mysql/:/data/db
