version: '3'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "capitan.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - 8000:8000
    volumes:
      - ./:/capitan/
      - /var/run/docker.sock:/var/run/docker.sock
