version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/capitan/
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:5.7
    volumes:
      - ~/.docker-volumes/capitan/mysql/:/data/db
